name: hmtpbsa docker push
on:
  push:
    tags:
      - v*

env:
  APP_NAME: hmtpbsa
  DOCKER_REPO: dplc/hmtpbsa

jobs:

  hmtloop_CD:
    name: build and push Docker image to DP docker image repo
    runs-on: self-hosted

    steps:
    - name: checkout repo
      uses: actions/checkout@v2

    - name: login
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.DPLC_REGISTRY }}
        username: ${{ secrets.DPLC_USERNAME }}
        password: ${{ secrets.DPLC_PASSWORD }}

    - name: Generate App Version
      run: echo APP_VERSION=`git describe --tags --always` >> $GITHUB_ENV

    - name: build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./containers/Dockerfile.dplc
        push: true
        tags: ${{ secrets.DPLC_REGISTRY }}/dplc/hmtpbsa:${{ env.APP_VERSION }}
