name: MMPBSA unittest
on: [push]

jobs:
  MMPBSA_unittest:
    runs-on: self-hosted
    container: dockerymh/hmtpbsa:gmx_openmpi_patch
    
    steps:
    - name: checkout repo
      uses: actions/checkout@v2
        
    - name: install hmtpbsa
      shell: bash
      run: |
        source activate amber21
        python setup.py install

    - name: run unittest
      shell: bash
      run: |
        source activate amber21
        cd tests
        bash cmd.sh
